/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PlayerRouteImport } from './routes/$player'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as MapsIndexRouteImport } from './routes/maps/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$player-id'
import { Route as MatchesMatchRouteImport } from './routes/matches/$match'
import { Route as MapsMapRouteImport } from './routes/maps/$map'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/$player',
  path: '/$player',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$player-id',
  path: '/players/$player-id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchRoute = MatchesMatchRouteImport.update({
  id: '/matches/$match',
  path: '/matches/$match',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapRoute = MapsMapRouteImport.update({
  id: '/maps/$map',
  path: '/maps/$map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$player': typeof PlayerRoute
  '/rules': typeof RulesRoute
  '/maps/$map': typeof MapsMapRoute
  '/matches/$match': typeof MatchesMatchRoute
  '/players/$player-id': typeof PlayersPlayerIdRoute
  '/events/': typeof EventsIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$player': typeof PlayerRoute
  '/rules': typeof RulesRoute
  '/maps/$map': typeof MapsMapRoute
  '/matches/$match': typeof MatchesMatchRoute
  '/players/$player-id': typeof PlayersPlayerIdRoute
  '/events': typeof EventsIndexRoute
  '/maps': typeof MapsIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$player': typeof PlayerRoute
  '/rules': typeof RulesRoute
  '/maps/$map': typeof MapsMapRoute
  '/matches/$match': typeof MatchesMatchRoute
  '/players/$player-id': typeof PlayersPlayerIdRoute
  '/events/': typeof EventsIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$player'
    | '/rules'
    | '/maps/$map'
    | '/matches/$match'
    | '/players/$player-id'
    | '/events/'
    | '/maps/'
    | '/matches/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$player'
    | '/rules'
    | '/maps/$map'
    | '/matches/$match'
    | '/players/$player-id'
    | '/events'
    | '/maps'
    | '/matches'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$player'
    | '/rules'
    | '/maps/$map'
    | '/matches/$match'
    | '/players/$player-id'
    | '/events/'
    | '/maps/'
    | '/matches/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerRoute: typeof PlayerRoute
  RulesRoute: typeof RulesRoute
  MapsMapRoute: typeof MapsMapRoute
  MatchesMatchRoute: typeof MatchesMatchRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MapsIndexRoute: typeof MapsIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$player': {
      id: '/$player'
      path: '/$player'
      fullPath: '/$player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/': {
      id: '/maps/'
      path: '/maps'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$player-id': {
      id: '/players/$player-id'
      path: '/players/$player-id'
      fullPath: '/players/$player-id'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$match': {
      id: '/matches/$match'
      path: '/matches/$match'
      fullPath: '/matches/$match'
      preLoaderRoute: typeof MatchesMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$map': {
      id: '/maps/$map'
      path: '/maps/$map'
      fullPath: '/maps/$map'
      preLoaderRoute: typeof MapsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerRoute: PlayerRoute,
  RulesRoute: RulesRoute,
  MapsMapRoute: MapsMapRoute,
  MatchesMatchRoute: MatchesMatchRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  MapsIndexRoute: MapsIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
